@startuml DiagramaClases
hide circle

Class Pantalla{
    btnCancelar
    btnConfirmar
    gridEventosSismicos
    opcRRES()
    abrirVentana()
    TomarSeleccionEventoSismico()
    mostrarEventoSismico()
}

Class Gestor{
    nuevaRevision()
    buscarEventosSismicos()
    ordenarEventoSismico()
    TomarSeleccionEventoSismico()
}

Class EventoSismico{
    existeEventoSismico()
    esPendienteRevision()
    getDatosPrincipales()
    getFechaHoradeOcurrencia()
    getLatitudEp()
    getLongitudEp()
    getLatitudHip()
    getLongHip()
    getMagnitud()
}

Class Estado{
    esAutoDetectado()
    esPendienteRevision()
}


'relaciones

Pantalla .left.> Gestor
Gestor .right.> Pantalla
Gestor ..> EventoSismico
EventoSismico -right-> Estado: "1 Estado"


@enduml
