@startuml DiagramaClases
hide circle

Class Pantalla{
    opcRRES()
    abrirVentana()
    TomarSeleccionEventoSismico()
    mostrarEventoSismico()
}

Class Gestor{
    nuevaRevision()
    buscarEventosSismicos()
    ordenarEventoSismico()
    TomarSeleccionEventoSismico()
}

Class EventoSismico{
    existeEventoSismico()
    esPendienteRevision()
    getDatosPrincipales()
    getFechaHoradeOcurrencia()
    getLatitudEp()
    getLongitudEp()
    getLatitudHip()
    getLongHip()
    getMagnitud()
}

Class Estado{
    esAutoDetectado()
    esPendienteRevision()
}

'Relaciones entre clases'
Pantalla .left.> Gestor
Gestor ..> Pantalla
Gestor .up.> EventoSismico
EventoSismico -right-> Estado: "1 Estado "

@enduml
