@startuml DiagramaClases
hide circle

Class Pantalla{
    btnCancelar
    btnConfirmar
    gridEventosSismicos
    opcRRES()
    abrirVentana()
    TomarSeleccionEventoSismico()
    mostrarEventoSismico()
}

Class Gestor{r
    nuevaRevision()
    buscarEventosSismicos()
    ordenarEventoSismico()
    TomarSeleccionEventoSismico()
}

Class EventoSismico{
    existeEventoSismico()
    esPendienteRevision()
    getDatosPrincipales()
    getFechaHoradeOcurrencia()
    getLatitudEp()
    getLongitudEp()
    getLatitudHip()
    getLongHip()
    getMagnitud()
}

Class Estado{
    esAutoDetectado()
    esPendienteRevision()
}


@enduml